require('core.plugin_config.nvim-tree')
require('core.plugin_config.treesitter')
require('core.plugin_config.telescope')
require('core.plugin_config.lsp_config')
require('core.plugin_config.completion')
require('core.plugin_config.commandline')
require('core.plugin_config.autopairs')
require('core.plugin_config.buffers')
require('core.plugin_config.indent_blankline')
require('core.plugin_config.gitsigns')
require('core.plugin_config.lspfonts')
require('core.plugin_config.live_error')
require('core.plugin_config.commentry')
require('core.plugin_config.notify')
require('core.plugin_config.lualine')

